#!/bin/bash
#Copyright (c) 2016 Alces Software Ltd
#Source the settings
. settings
#Create stack
aws cloudformation create-stack \
	--stack-name ${CLUSTER_NAME}-network \
	--template-body file://templates/network.json
##Wait for Stack completion here
sleep 120
for resource in VPCID GATEWAYID ROUTETABLEID SUBNETID NETWORKACL SECURITYGROUP; do
  id=$(aws cloudformation describe-stacks --stack-name ${CLUSTER_NAME}-network | grep $resource | awk '{print $4}');
  echo "${resource}=\"${id}\"" >> settings;
done
