#!/bin/bash

DOMAIN=$(hostname -d | grep -o "\." | wc -l)
if [ "$DOMAIN" == "2" ];
then
  DOMAIN=$(hostname -d)
elif [ "$DOMAIN" == "3" ];
then
  DOMAIN=$(hostname -d | cut -d . -f 2-4)
fi
REALM=`echo $DOMAIN | sed -e 's/\(.*\)/\U\1/'`

pull_config() {

  _s3cmd=/opt/clusterware/opt/s3cmd/s3cmd
  source /opt/clusterware/etc/cluster-customizer.rc
  storage_config_dir="/opt/symphony-directory/etc"
  mkdir -p $storage_config_dir
  storage_config="/opt/symphony-directory/etc/storage_config"
  if [ -z $cw_CLUSTER_CUSTOMIZER_access_key_id ]; then
    source /opt/clusterware/etc/config/cluster/instance-aws.rc
    source /opt/clusterware/etc/config/cluster/instance-aws-iam.rc
    cw_CLUSTER_CUSTOMIZER_bucket="s3://alces-flight-${cw_INSTANCE_aws_account_hash}"
    cw_CLUSTER_CUSTOMIZER_region=$(curl -sL http://169.254.169.254/latest/meta-data/placement/availability-zone/ | sed 's/.$//')
    $_s3cmd --access_key="${cw_INSTANCE_aws_iam_role_access_key_id}" \
            --secret_key="${cw_INSTANCE_aws_iam_role_secret_access_key}" \
            --access_token="${cw_INSTANCE_aws_iam_role_security_token}" \
            --region ${cw_CLUSTER_CUSTOMIZER_region} \
            get ${cw_CLUSTER_CUSTOMIZER_bucket}/directory/${REALM}/storage_config \
            ${storage_config}
  else
    $_s3cmd --access_key=${cw_CLUSTER_CUSTOMIZER_access_key_id} \
            --secret_key=${cw_CLUSTER_CUSTOMIZER_secret_access_key} \
            --region=${cw_CLUSTER_CUSTOMIZER_region} \
            get ${cw_CLUSTER_CUSTOMIZER_bucket}/directory/${REALM}/storage_config \
            ${storage_config}
  fi
  chmod 0640 ${storage_config}
  source ${storage_config}
  setup_storage

}

setup_storage() {

  mount_list="/opt/symphony-directory/etc/mounts"
  showmount -e ${STORAGE_PRV} | awk 'NR >1 {print $1}' > $mount_list
  while read mounts; do
    mkdir -p $mounts
    echo "${STORAGE_PRV}:/${mounts} $mounts nfs rsize=8192,wsize=8192,timeo=16,intr" >> /etc/fstab
    mount -a
  done < "$mount_list"

}

pull_config
